### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by jrmcdona** [GeekyAnts/NativeBase-KitchenSink#1]
Hi All,
Getting this error after going through the install steps the hitting play in xcode. Getting this error, what do you think I need to do here?  Tried clear npm cache.

<img width="275" alt="screen shot 2016-10-17 at 9 45 30 pm" src="https://cloud.githubusercontent.com/assets/4327773/19462530/103541d0-94b3-11e6-8d1b-346ebec5e40b.png">

Thanks

**Comment by SupriyaKalghatgi** [comment]
@jrmcdona Yea this happens due to renaming (only case) any folder.
Try renaming the folder as per AppNavigator.
Will fix it soon

**Comment by SupriyaKalghatgi** [comment]
@jrmcdona Fixed
Try pulling the latest from `master`

**Comment by jrmcdona** [comment]
Fixed! Thank you
