### ISSUE TITLE
How do you record screenshot GIFs?

### ISSUE THREAD

**Issue by shaundon** [GeekyAnts/NativeBase-KitchenSink#101]
Hey - sorry for spamming your issues with a query, but I was unable to find an answer on your forum, in your codebase, or on Slack.

What method are you using to record GIFs in the `/screenshots` folder? 

I work on [this repo](https://github.com/skyscanner/backpack), and we're looking for a good way to showcase our React Native components on our docs site. Currently we just use screenshots (like on [this page](https://backpack.github.io/components/native/picker)), but we're exploring GIFs. 

Our issue is that there'll be a lot of overhead with recording GIFs every time the component changes.

So, how do you folks manage it? 😄

**Comment by SupriyaKalghatgi** [comment]
licecap

**Comment by SupriyaKalghatgi** [comment]
Google for such queries

**Comment by gianpaj** [comment]
It depends on what mobile platform you want to record (ios or android), then do you want to record the emulator/simulator (then depends if you have a Windows, Mac, etc.) or an actual physical device (for example you need record push notifications coming in).

I would Google:
```
record ios simulator screen
record android emulator screen

record android app
record ios app
```
there are many ways to skin the cat, as they say.

First, try to record a video, once you have that, it's easy to convert a .mp4, etc. into a gif.

I have a Mac and with this instructions, you can record anything on your computer screen and convert it into a Gif.
https://gist.github.com/dergachev/4627207

Of course, there are also apps like Giphy capture and Gif Brewery.

FYI: I agree. Github should be used for project-related questions/issue. Google or your co-worker might have the best answer

**Comment by shaundon** [comment]
Thanks for the advice @gianpaj. I think I may have been misunderstood - I meant how do **you specifically** capture these screenshots? 

The overhead with having to re-record a GIF for every visual change you make would be quite high, so I assumed that you're using an automated tool to do it, for example a Storybook plugin.

**Comment by gianpaj** [comment]
oh, I see. Good question. There must be an automated way to do that.

The only thing I can think of is using an e2e UI test tool like [Detox](https://github.com/wix/detox) and have some JavaScript start a recording of the emulator/simulator screen area.

For plain images (no gifs) you can find an example here:
https://github.com/wix/detox/issues/171#issuecomment-361663265
