### ISSUE TITLE
Confusing docs?

### ISSUE THREAD

**Issue by xemasiv** [GeekyAnts/NativeBase-KitchenSink#108]
Docs say:

1. Pure React Native App with react-navigation on branch master
2. Pure React Native App with RNRF on branch RNRF
3. An Expo app with CRNA and react-navigation on branch CRNA
4. A React App with NativeBase for web on branch web-support

So following this, assuming I'm on the branch `master`.

```
git clone git@github.com:GeekyAnts/NativeBase-KitchenSink.git
cd NativeBase-KitchenSink
yarn
react-native link react-native-vector-icons
```

Got error about /src/boot/setup.js asking for Expo.
Maybe I'm dumb for not knowing what to do with this error,
I tried `npm install expo --save` too, it just beget another set of issues.

But before that, I thought the Expo stuff was on number 3? On branch `CRNA`?
I ran `git branch` to double check, it says I'm on `master`.

I also tried looking for issues (open/closed) but haven't seen anything similar.

Any thoughts? Lol

**Comment by SupriyaKalghatgi** [comment]
@xemasiv Fixed it on `master`

**Comment by xemasiv** [comment]
Appreciate your fast response Supriya, thank you very much.
