### ISSUE TITLE
Unknown named module: 'react/lib/ReactNativePropRegistry'

### ISSUE THREAD

**Issue by DaniloMeritocracy** [GeekyAnts/NativeBase-KitchenSink#11]
This error is appearing in the Android emulator.

My package.json:

```
"dependencies": {
    "native-base": "^0.5.18",
    "react": "^15.4.0",
    "react-native": "^0.38.0",
    "react-native-vector-icons": "^2.0.3"
}
```

I cloned this repo, edited the package.json as above (because in past I tried with the default package and it didn't work) and here we are.

I read something here, but nothing. https://github.com/GeekyAnts/NativeBase/issues/307

**Comment by SupriyaKalghatgi** [comment]
@DaniloMeritocracy Very soon we will update this

**Comment by DaniloMeritocracy** [comment]
Thank you! I will stay on hold.

**Comment by SupriyaKalghatgi** [comment]
@DaniloMeritocracy You said you tried the default package and it didn't work
Could you please share the issue you are facing

**Comment by DaniloMeritocracy** [comment]
> @SupriyaKalghatgi following the README, I just clone the repo and then npm install.
> 
> The output is this:
> 
> npm ERR! peerinvalid The package react-native@0.35.0 does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer native-base@0.5.13 wants react-native@>=0.26.0
> npm ERR! peerinvalid Peer react-native-navigation-redux-helpers@0.4.1 wants react-native@>=0.28.0
> npm ERR! peerinvalid Peer jest-react-native@16.1.0 wants react-native@>=0.36.0

**Comment by DaniloMeritocracy** [comment]
Hi @SupriyaKalghatgi 
is there any update?

**Comment by SupriyaKalghatgi** [comment]
Fixed with latest commit [0.5.18](https://github.com/GeekyAnts/NativeBase-KitchenSink/releases/tag/0.5.18)

**Comment by SupriyaKalghatgi** [comment]
@DaniloMeritocracy Is it happening only for Android?

**Comment by DaniloMeritocracy** [comment]
@SupriyaKalghatgi I don't know, I'm working on Ubuntu so I can't test it on iOS, I'm sorry! Can you replicate the problem on Android?

**Comment by SupriyaKalghatgi** [comment]
@DaniloMeritocracy Ok will try to.

**Comment by febeling** [comment]
The package.json still refers to 1.6 of `react-native-easy-grid`, which references the file the old way (see GeekyAnts/NativeBase#336). 

When I changed its version spec to 1.7 it worked.

**Comment by DaniloMeritocracy** [comment]
@febeling you're right! Thanks.
