### ISSUE TITLE
drawer-cover.png is a jpg

### ISSUE THREAD

**Issue by tkserver** [GeekyAnts/NativeBase-KitchenSink#111]
React doesn't seem to have an issue with this, but the file type of drawer-cover.png is actually a JPG.

**Comment by tkserver** [comment]
Same goes for launchscreen-bg.png.  Guessing there will be a few more but I won't bother posting those.

**Comment by SupriyaKalghatgi** [comment]
Thank you for this information
The basic purpose of this repo is to showcase NativeBase components
