### ISSUE TITLE
Sidebar close issue

### ISSUE THREAD

**Issue by gouravchd** [GeekyAnts/NativeBase-KitchenSink#112]
Sidebar doesn't close when multiple click on sidebar menu. Background sceen is changing but sidebar not close.

**Comment by SupriyaKalghatgi** [comment]
is it still happening with latest update?

**Comment by SupriyaKalghatgi** [comment]
@gouravchd Any updates?

**Comment by gouravchd** [comment]
Now giving an error http://prntscr.com/k9gmtx
