### ISSUE TITLE
Warning: Received `true` for a non-boolean attribute `uppercase`.

### ISSUE THREAD

**Issue by dinaomari90** [GeekyAnts/NativeBase-KitchenSink#121]
Im getting this error when i run `npm start`
![native](https://user-images.githubusercontent.com/38206630/41199234-aca86c24-6c96-11e8-8426-93ed2798a04e.png)
![err](https://user-images.githubusercontent.com/38206630/41199241-bdd4ae68-6c96-11e8-934f-3a5423c64cf6.png)

**Comment by SupriyaKalghatgi** [comment]
yes we are aware of this
But still the project runs

**Comment by vinpez** [comment]
We're still experiencing this issue. Is there an expected fix on the way?

**Comment by tonypee** [comment]
Im experiencing it

**Comment by elektronik2k5** [comment]
Yup, everything works, but the console is highly spammed by these messages.

**Comment by vinpez** [comment]
Would really love a fix. If the Native Base team is swamped, my team can submit a PR (let me know).

**Comment by Kif11** [comment]
@vinpez I would love to see a fix for this.
