### ISSUE TITLE
react native 0.56版本  问题

### ISSUE THREAD

**Issue by 131986777** [GeekyAnts/NativeBase-KitchenSink#125]
0.56版本出现
import type {CommandT} from './commands';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Module._compile (E:\reactWorkspace\NativeBase-KitchenSink\node_modules\pi
rates\lib\index.js:91:24)
    at Module._extensions..js (module.js:646:10)
    at Object.newLoader [as .js] (E:\reactWorkspace\NativeBase-KitchenSink\node_
modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

我的解决方法是降级到0.55.4 
希望有大神能有0.56不降级的办法 谢谢

**Comment by SupriyaKalghatgi** [comment]
Share package.json

**Comment by 131986777** [comment]
{
  "name": "NativebaseKitchenSink",
  "version": "2.7.0",
  "private": true,
  "devDependencies": {
    "babel-eslint": "7.2.3",
    "eslint": "4.4.1",
    "eslint-plugin-flowtype": "2.35.0",
    "eslint-plugin-import": "2.7.0",
    "eslint-plugin-jsx-a11y": "6.0.2",
    "eslint-plugin-prettier": "2.1.2",
    "eslint-plugin-react": "7.1.0",
    "eslint-plugin-react-native": "3.0.1",
    "flow-bin": "0.52.0",
    "flow-typed": "2.1.5",
    "husky": "0.14.3",
    "jest": "23.3.0",
    "prettier": "1.5.3",
    "react-test-renderer": "16.4.1"
  },
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "react-native"
  },
  "dependencies": {
    "color": "1.0.3",
    "lodash": "4.13.1",
    "moment": "2.13.0",
    "native-base": "2.7.0",
    "react": "16.4.1",
    "react-native": "^0.55.4",
    "react-navigation": "1.5.0"
  }
}

**Comment by 131986777** [comment]
{
  "name": "NativebaseKitchenSink",
  "version": "2.7.0",
  "private": true,
  "devDependencies": {
    "babel-eslint": "7.2.3",
    "eslint": "4.4.1",
    "eslint-plugin-flowtype": "2.35.0",
    "eslint-plugin-import": "2.7.0",
    "eslint-plugin-jsx-a11y": "6.0.2",
    "eslint-plugin-prettier": "2.1.2",
    "eslint-plugin-react": "7.1.0",
    "eslint-plugin-react-native": "3.0.1",
    "flow-bin": "0.52.0",
    "flow-typed": "2.1.5",
    "husky": "0.14.3",
    "jest": "23.3.0",
    "prettier": "1.5.3",
    "react-test-renderer": "16.4.1"
  },
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "react-native"
  },
  "dependencies": {
    "color": "1.0.3",
    "lodash": "4.13.1",
    "moment": "2.13.0",
    "native-base": "2.7.0",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-navigation": "1.5.0"
  }
}
  这是之前的

**Comment by SupriyaKalghatgi** [comment]
why 2 package.json?

**Comment by 131986777** [comment]
最后一个 是出问题的版本 关于这个 报错 是react-native“：”0.56.0“，  的原因  官网脚手架拉下来就报错，我自己在建项目的时候 会指定0.55.4   这样能创建成功，我看大佬 升级0.56.0了 希望问问大佬是否解决了这个问题

**Comment by SupriyaKalghatgi** [comment]
Please post in English

**Comment by 131986777** [comment]
sorry    The last one is wrong version of this error is the react - native 0.56.0 ":" ", website scaffolding down the cause of an error, my own project under construction can specify 0.55.4 that can create success, I saw a big upgrade 0.56.0 hope ask bosses if solved the problem

**Comment by SupriyaKalghatgi** [comment]
Here is the latest React Native and NativeBase, tested and working fine
https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/package.json

**Comment by SupriyaKalghatgi** [comment]
I dd'nt face this
`import type {CommandT} from './commands';`

Try deleting node_modules, clear cache, clear watchman and run

**Comment by 131986777** [comment]
The reason for guessing has been solved, I think it is because I will use NPM after redeleting with yarn. Thank you
