### ISSUE TITLE
Is it possible using both of "CRNA" and "Web-support"?

### ISSUE THREAD

**Issue by devjiro76** [GeekyAnts/NativeBase-KitchenSink#126]
Hi. I really love this amazing UI framework.
I have one question about using this framework for both of "CRNA" and "Web-Support" via one source code.

What I want to do is developing only one source code. and...
1. I want to check my source on Browser (like using 'Web-Support' Branch)
2. and I also want to make native app and check this on Expo (like using 'CRNA' branch)
I want to do these at one time.

Is it possible?
I cloned this repo on my local.
and merge 'CRNA' on 'Web-Support' branch with '--allow-unrelated-histories' flag.
but there are huge conflict and I am wondering whether this is possible or not.

if anyone have answer please let me know.
If this is not possible, I'll go on 'CRNA" branch

**Comment by SupriyaKalghatgi** [comment]
I have never tried that, no idea
