### ISSUE TITLE
Command `link` unrecognized.

### ISSUE THREAD

**Issue by hdamis** [GeekyAnts/NativeBase-KitchenSink#127]
I am trying to install NativeBase-KitchenSink-master
cd NativeBase-KitchenSink-master
yarn
react-native link react-native-vector-icons
but I got this error
C:\React\NativeBase-KitchenSink-master>react-native link react-native-vector-icons
Command `link` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.
just to now node version v8.11.2

**Comment by SupriyaKalghatgi** [comment]
@hdamis 
> C:\React\NativeBase-KitchenSink-master>react-native link react-native-vector-icons
Command link unrecognized. Make sure that you have run npm install and that you are inside a react-native project.

The error is explaining you whats wrong

**Comment by hdamis** [comment]
@SupriyaKalghatgi
I run npm install inside a react native project. but the same.
what I did actually.
I donwload the NativeBase-KitchenSink-master.zip then extracted it to  C:\React\NativeBase-KitchenSink-master then I typed 
C:\React\ cd NativeBase-KitchenSink-master
and inside this folder I enter the follwing:  
yarn
react-native link react-native-vector-icons
but I got the error above.

**Comment by SupriyaKalghatgi** [comment]
share node, npm, react native cli version

**Comment by hdamis** [comment]
C:\Users\hani>react-native -v
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory

C:\Users\hani>npm -v
5.6.0

C:\Users\hani>node -v
v8.11.3

**Comment by hdamis** [comment]
no I got the following

C:\React\NativeBase-KitchenSink-master>react-native link react-native-vector-icons
C:\React\NativeBase-KitchenSink-master\node_modules\react-native\local-cli\cliEntry.js:30
import type {CommandT} from './commands';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (C:\React\NativeBase-KitchenSink-master\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (C:\React\NativeBase-KitchenSink-master\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

C:\React\NativeBase-KitchenSink-master>

**Comment by hdamis** [comment]
@SupriyaKalghatgi 
any idea please.

**Comment by Juniper11** [comment]
I have the same issue with "link" being unrecognizable.

None of the advice out there about deleting node modules and reinstalling them seems to work for me.
https://github.com/Polidea/react-native-ble-plx/issues/98

**Comment by liambrennan** [comment]
The issue is probably the fact that you are running on Windows, and windows has an issue with react native 0.56.00(which the project was recently upgraded to):
https://github.com/facebook/react-native/issues/20015

I have no idea how to fix this issue, however if you checkout the commit('Added screenshots for 2.6.1' - 9dd9292) from before that upgrade
https://github.com/GeekyAnts/NativeBase-KitchenSink/commit/9dd9292206e24321b8eebdedb839b7262123abdc

and run as normal, it should be okay. Not a proper solution, but will get it working on your machine.
Worked for me anyway.

**Comment by SupriyaKalghatgi** [comment]
> Command link unrecognized. Make sure that you have run npm install and that you are inside a react-native project.

It is clear from this statement, that the issue is not with this repo, but with the system environment

**Comment by xyq86565379** [comment]
> The issue is probably the fact that you are running on Windows, and windows has an issue with react native 0.56.00(which the project was recently upgraded to):
> [facebook/react-native#20015](https://github.com/facebook/react-native/issues/20015)
> 
> I have no idea how to fix this issue, however if you checkout the commit('Added screenshots for 2.6.1' - [9dd9292](https://github.com/GeekyAnts/NativeBase-KitchenSink/commit/9dd9292206e24321b8eebdedb839b7262123abdc)) from before that upgrade
> [9dd9292](https://github.com/GeekyAnts/NativeBase-KitchenSink/commit/9dd9292206e24321b8eebdedb839b7262123abdc)
> 
> and run as normal, it should be okay. Not a proper solution, but will get it working on your machine.
> Worked for me anyway.

MacOs can't work either
