### ISSUE TITLE
List items rendering without bottom borders

### ISSUE THREAD

**Issue by dkimot** [GeekyAnts/NativeBase-KitchenSink#128]
On some of the list items, there is no bottom border. I cloned the master repo about 20 minutes ago and did nothing else. Simply ran `npm i` and `react-native link` and `react-native run-ios --simulator="iPad Pro (9.7-inch)`.

This is what I'm seeing:
<img width="653" alt="image" src="https://user-images.githubusercontent.com/20249639/43042259-1f1146e0-8d36-11e8-9ec9-a53eaf9e3aa6.png">
<img width="656" alt="image" src="https://user-images.githubusercontent.com/20249639/43042261-299728b4-8d36-11e8-8515-4c6e0d7456f5.png">

I'm fairly new to React Native and don't know what would cause this or really where to start, however, this problem only happens when simulating on an iPad.

**Comment by dkimot** [comment]
I did change the XCode Project to universal.

**Comment by SupriyaKalghatgi** [comment]
This happens only in case of simulators and emulators and not in case if you run this on device.

You can try to zoom-in the simulator to see the visible border bottom
