### ISSUE TITLE
open row dynamically in multi-swipe-list

### ISSUE THREAD

**Issue by PriyankaAshu** [GeekyAnts/NativeBase-KitchenSink#131]
I am using multi swipe list, I want to open row dynamically by calling some function. Not by manually left swipe. Here is my code below in openCurrenRow() How can I open row for particular row.

<List
              dataSource={this.ds.cloneWithRows(this.state.listViewData)}
               renderRow={ (data, secId, rowId, rowMap) => 
                   
                <ListItem style={{borderBottomWidth: 1,marginLeft: 0, backgroundColor : data.rowBg}}>
                  
                  <Left>
                  { 
                    this.state.rmvCircle && 
                   
                    <Icon onPress={()=>this.openCurrenRow(data, secId, rowId, rowMap)} style={{color:'red'}} name="md-remove-circle" />
                  }
                    
                    <TouchableOpacity onPress={()=>this.redir(data)}>
                      <Text numberOfLines={1}>
                        {data.text}
                      </Text>
                    </TouchableOpacity>  
                  </Left>
                </ListItem>}

                
                renderRightHiddenRow={(data, secId, rowId, rowMap) =>
                  <Button
                    full
                    danger
                    onPress={_ => this.clearNotificationPrompt(secId, rowId, rowMap, data.logId,'single')}
                    style={{
                      flex: 1,
                      alignItems: "center",
                      justifyContent: "center"
                    }}
                  >
                    <Text>Delete</Text>
                  </Button>}
                  rightOpenValue={-85}
                  
                  disableRightSwipe
               />

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/1611
