### ISSUE TITLE
Image not displayed for Card -> Card Image

### ISSUE THREAD

**Issue by murtraja** [GeekyAnts/NativeBase-KitchenSink#135]
![card_image](https://user-images.githubusercontent.com/7806954/45024532-de6a8900-b056-11e8-9075-f3df34aa04de.jpg)

**Comment by suvenduchhatoi** [comment]
@murtraja  can you share your code snippet please

**Comment by suvenduchhatoi** [comment]
@murtraja Please check for proper path to image directory. It's working fine... 
![screen shot 1440-06-14 at 12 39 56 am](https://user-images.githubusercontent.com/44160581/52971917-2a2fa580-33df-11e9-8897-99ce040af2bc.png)
