### ISSUE TITLE
Checkbox click not working

### ISSUE THREAD

**Issue by hrshtplwl3** [GeekyAnts/NativeBase-KitchenSink#137]
import {  Body, List, ListItem, Text, CheckBox} from "native-base";

----

constructor() {
    super();
    this.state = {
      shareCommission: false
    };
  }

  _checkBoxHandler() {
    this.setState({
      shareCommission: !this.state.shareCommission
    });
  }

----

<List
     dataArray={datas}
     renderRow={data => (
          <ListItem button onPress={() => this._checkBoxHandler()}>
                **<CheckBox
                    color="green"
                    checked={this.state.shareCommission}
                    onPress={() => this._checkBoxHandler()}
                    />**
                    </ListItem>
                  )}
/>

**Comment by SupriyaKalghatgi** [comment]
works fine for me
![checkbox](https://user-images.githubusercontent.com/13464885/52995010-685cb180-343f-11e9-9c7c-7c0d0a14e6a5.gif)
