### ISSUE TITLE
App Loading Issues

### ISSUE THREAD

**Issue by jashparekh** [GeekyAnts/NativeBase-KitchenSink#142]
Hi,

I followed the instructions in readme and also tried debugging and stackoverflowing the following issue. Please let me know where I am going wrong with this.

I tried both npm start as well as npm start ios, both of them are stuck at `Loading dependency graph, done`.

 React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
      Memory: 96.02 MB / 4.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.3.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 15.4.2 => 15.4.2 
      react-native: ^0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by jashparekh** [comment]
Also, few errors like these

Build system information

error: Multiple commands produce '/Users/jashparekh/Library/Developer/Xcode/DerivedData/build/Build/Products/Debug-iphonesimulator/NativebaseKitchenSink.app/Ionicons.ttf':
1) Target 'NativebaseKitchenSink' (project 'NativebaseKitchenSink') has copy command from '/Users/jashparekh/Projects/NativeBase-KitchenSink/node_modules/native-base/Fonts/Ionicons.ttf' to '/Users/jashparekh/Library/Developer/Xcode/DerivedData/build/Build/Products/Debug-iphonesimulator/NativebaseKitchenSink.app/Ionicons.ttf'
2) Target 'NativebaseKitchenSink' (project 'NativebaseKitchenSink') has copy command from '/Users/jashparekh/Projects/NativeBase-KitchenSink/node_modules/react-native-vector-icons/Fonts/Ionicons.ttf' to '/Users/jashparekh/Library/Developer/Xcode/DerivedData/build/Build/Products/Debug-iphonesimulator/NativebaseKitchenSink.app/Ionicons.ttf

**Comment by suvenduchhatoi** [comment]
@jashparekh  Have you followed these steps ![screen shot 1440-06-06 at 4 27 20 pm](https://user-images.githubusercontent.com/44160581/52559051-397c8500-2e1a-11e9-9f41-40688cc2ab41.png)
and then run `react-native run-ios`?

**Comment by SupriyaKalghatgi** [comment]
#147
