### ISSUE TITLE
react-native run-android error 

### ISSUE THREAD

**Issue by yohanes-ai** [GeekyAnts/NativeBase-KitchenSink#143]
I trying to running this project. My emulator already running. So I followed the documentation 
```
git clone git@github.com:GeekyAnts/NativeBase-KitchenSink.git
cd NativeBase-KitchenSink
yarn
react-native link react-native-vector-icons
```

than
`react-native run-android`

After that, I got following error

> > Configure project :app
> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> Checking the license for package Android SDK Build-Tools 27.0.3 in C:\Users\root\AppData\Local\Android\Sdk\licenses
> Warning: License for package Android SDK Build-Tools 27.0.3 not accepted.
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':app'.
> > Failed to install the following Android SDK packages as some licences have not been accepted.
>      build-tools;27.0.3 Android SDK Build-Tools 27.0.3
>   To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
>   Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
> 
>   Using Android SDK: C:\Users\root\AppData\Local\Android\Sdk
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4s
> Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/getting-started.html

I have try to

1. Delete `node_modules` and doing the same things to install `yarn and blablabla`
2. Accept all license by doing this `tools/bin/sdkmanager --licenses`

What I missed here? Thanks

**Comment by gurolcetin** [comment]
I also get the same error. Did you solve the error?

**Comment by suvenduchhatoi** [comment]
@yohanes-ai 
First of all, your Android Emulator should already been running from Android Studio before running the command `react-native run-android`
![screen shot 1440-06-06 at 4 43 34 pm](https://user-images.githubusercontent.com/44160581/52559749-31bde000-2e1c-11e9-9904-d83b1701ebb9.png)
If you have followed the above step, still getting error, run `./sdkmanager --update` and run again... But, certainly, not a native-base issue...

**Comment by suvenduchhatoi** [comment]
After following the installation steps-
 -> run `react-native upgrade`
 -> run `react-native link react-native-vector-icons`
 -> run `react-native run-android` or `react-native run-ios`

**Comment by SupriyaKalghatgi** [comment]
#147
