### ISSUE TITLE
NativeBase-KitchenSink 2.5.0 failed to build for both iOS and Android

### ISSUE THREAD

**Issue by sekhuat** [GeekyAnts/NativeBase-KitchenSink#147]
I had downloaded the NativeBase-KitchenSink 2.5.0 as zip file and perform the following steps however it failed to build.

1. Unzip the downloaded file into my project folder
2. run `npm install` in my project folder
3. run `react-native link` in my project folder

Below is my system info when run `react-native info`

```
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
      Memory: 51.29 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /opt/local/bin/node
      Yarn: 1.12.3 - /opt/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /opt/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 14, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.0, 27.0.1, 27.0.3, 28.0.0, 28.0.0, 28.0.1, 28.0.2, 28.0.3
        System Images: android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: ^0.58.4 => 0.58.4 

```

When I tried to build the project for android with `react-native run-android` I got the `aapt: error: resource android:attr/dialogcornerradius not found.` error. To solve this issue I need to change the ./android/guild.gradle file to set the  compileSdkVersion and targetSdkVersion = 28 as below.

```
   ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "27.1.1"
    }
```

In additional I also found that the package name for the MainApplication.java and MainActivity.java is `io.market.nativebase.geekyants.nativebasekitchensink`  however the actual folder structure is `./android/app/src/main/java/com/nativebasekitchensink` which does not match the package name and this will also cause error during building the project for android. I need to change the package name to `com.nativebasekitchensink` in order to solve the issue. At last I am able to build and run the project on Android platform. Please update your document on the compileSdkVersion and targetSdkVersion so that user will not waste too much time to figure it out. As for the folder mismatch the package name you might want to fix it.

When I tried to build the project for iOS with `react-native run-ios` I got the following error:

   ```
   ld: symbol(s) not found for architecture x86_64
   clang: error
   : linker command failed with exit code 1 (use -v to see invocation)
```

To solve this issue I need to add the **JavaScriptCore.framework** into the “Linked Frameworks and Libraries” via xCode. Please fix the issue or update your document.

I had wasted almost 2 days to figure it out as I am new to Nativebase therefore I hope my feedback will help others to save time. Thank you.

**Comment by suvenduchhatoi** [comment]
1. run `react-native-upgrade`
2. run `react-native link react-native-vector-icons`
3. run `react-native run-android` or `react-native run-ios`

**Comment by SupriyaKalghatgi** [comment]
The latest on branch `master` is up and running
Apologies for inconvenience
