### ISSUE TITLE
Header, content and Footer overlays on top

### ISSUE THREAD

**Issue by dfantonio** [GeekyAnts/NativeBase-KitchenSink#156]
I'm trying to use the header, content and footer features of Native Base but it is not working even with the sample code:
`
render() {

    return (
      <Container>
        <Header>
          <Left>
            <Button transparent>
              <Icon name='menu' />
            </Button>
          </Left>
          <Body>
            <Title>Header</Title>
          </Body>
          <Right />
        </Header>
        <Content>
          <Text>
            This is Content Section
          </Text>
        </Content>
        <Footer>
          <FooterTab>
            <Button full>
              <Text>Footer</Text>
            </Button>
          </FooterTab>
        </Footer>
      </Container>
    );
  }
`
Version of react native: 0.57.1
Version of Native Base: 2.12.1

Here is how it looks on my Android:
![Screenshot_20190320-173236](https://user-images.githubusercontent.com/40124768/54717279-97496e80-4b36-11e9-9d42-842aa85130ba.png)

I can't figure out a reason for this, so I'm hoping someone can help me.

**Comment by SupriyaKalghatgi** [comment]
@dfantonio I checked this across the versions that you mentioned, couldn't reproduce this issue.
Check https://github.com/GeekyAnts/NativeBase-KitchenSink releases and try to install + run

**Comment by KenzoIkeizume** [comment]
This is a expo problem, check this on https://github.com/expo/expo/issues/71.

Include `style={{ marginTop: Expo.Constants.statusBarHeight }}` in your app

**Comment by smartcatdev** [comment]
@KenzoIkeizume 
I saw several other solution, but yours is the quickest fix;
