### ISSUE TITLE
Why is Codepush required?

### ISSUE THREAD

**Issue by kevando** [GeekyAnts/NativeBase-KitchenSink#17]
I just downloaded your demo app and it looks awesome. Thanks for putting together these awesome and helpful UI components.

I've never used codepush before, but it looks very helpful. My biggest worry is performance because my app is designed for offline.

**Comment by kevando** [comment]
Whoops, just realized this is the demo app.

**Comment by SupriyaKalghatgi** [comment]
Check [Native Starter Kit](https://github.com/start-react/native-starter-kit)
