### ISSUE TITLE
Error at npm start

### ISSUE THREAD

**Issue by FormidablePencil** [GeekyAnts/NativeBase-KitchenSink#180]
I've never reached out for help over any medium on the web so forgive me if I don't make self clear the first time. 
I've npm installed and fix audited then when I npm run start this spits out to the screen:
Looking for JS files in
   /Users/dennisaleksandrov/Documents/projects/NativeBase-KitchenSink 

Loading dependency graph...events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/dennisaleksandrov/Documents/projects/NativeBase-KitchenSink/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:223:5)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:129:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! NativebaseKitchenSink@2.12.0 start: `react-native start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the NativebaseKitchenSink@2.12.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dennisaleksandrov/.npm/_logs/2020-01-24T07_44_08_125Z-debug.log

**Comment by FDiskas** [comment]
```
brew update
brew install watchman
```
