### ISSUE TITLE
Adding badges to a Footer tab item

### ISSUE THREAD

**Issue by jrmcdona** [GeekyAnts/NativeBase-KitchenSink#2]
Hi All,
It is possible to use the Native base badge and assign it to one of the Footer tab items.  Much like you see with Facebook notifications.  I tried it using out of the box badge and Footer tab but they didn't seem to work together.  

I assume I could make my own badge and try to get it to work.

Is this something you all were planning to add?

Thanks!

**Comment by sanketsahusoft** [comment]
@jrmcdona Thanks for the suggestion. Though, this issue deserves a place in [NativeBase](https://github.com/GeekyAnts/NativeBase) repo. Can you please raise it there?
