### ISSUE TITLE
call undefined hexString() in base-theme.js

### ISSUE THREAD

**Issue by croustibat** [GeekyAnts/NativeBase-KitchenSink#21]
Hi,

when i launched `yarn upgrade`, the Color package  has been updated to 1.0.3.
then it raised an error with an undefined call to hexString() in themes/base-theme.js.

I fixed that changing 

`return color(this.toolbarDefaultBg).darken(0.2).hexString();` 

to

`return color(this.toolbarDefaultBg).darken(0.2).hex();`

**Comment by SupriyaKalghatgi** [comment]
@croustibat Do you find this issue with the latest of NativeBase KitchenSink?

**Comment by kyjak** [comment]
Actually have the same problem, and using the hex() just creates another JS error ...

**Comment by hewrin** [comment]
This still seems to be an issue in Nativebase 2.1.5

**Comment by vanish1984** [comment]
the same error in 2.1.3

**Comment by shivrajkumar** [comment]
If you had ejected the theme earlier and have updated to 2.1.5, just replace `hexString` with `hex` in the theme files.

**Comment by davidsneal** [comment]
Oddly for me (using 2.1.5) I had to change all instances of hex() to hexString()

**Comment by ckim16** [comment]
I'm currently using `"native-base": "^2.2.1"` and `"react-native": "^0.46.1"` and I get an error saying that `(0, _color2.default)(...).darken(...).hex is not a function`. Does this error have to with this issue here?

**Comment by cyrilf** [comment]
@ckim16 yep it does. As @davidsneal said, I had to do the reverse (updating all the `hex` function calls to `hexString` on my `commonColor` file.

**Comment by PauloCruz10** [comment]
ty

**Comment by ceefour** [comment]
So what is the recommended solution here?

When I try to `npm install --save color`, I noticed this:

```
+-- color@2.0.0
| `-- color-string@1.5.2
`-- expo@20.0.1
  `-- react-native-svg@5.3.0
    `-- color@0.11.4
      `-- color-string@0.3.0
```

So it seems that Expo SDK 2.0 still uses color 0.11.4, while nativebase requires color 1.x but didn't actually require it in the package.json (?)

Meanwhile, the latest color is 2.0.0 !

I'd love a solution that is most compatible with all packages.

**Comment by SupriyaKalghatgi** [comment]
@ceefour Did you check with the latest on `master` and `CRNA`?

**Comment by jmatsushita** [comment]
Hi there,

I did also run into this and I think that:
 - `.hexString()` is needed by Expo.
 - `.hex()` is needed if you don't use Expo.

I realised this after ejecting from Expo.

Cheers,

Jun

**Comment by StormFactory** [comment]
I'm running the following versions and still get the same error as @croustibat & @ckim16.
```
"expo": "^20.0.0",
"native-base": "^2.3.2",
"react": "16.0.0-alpha.12",
```
However @jmatsushita's suggestion worked in resolving the error.

**Comment by RobertHeim** [comment]
We do NOT use Expo and use the following versions:
```
"native-base": "^2.3.1",
"react-native": "^0.48.2",
```
getting 

`undefined is not a function (evaluating '(0, _color2.default)(this.toolbarDefaultBg).darken(0.2).hex()')`

**Comment by parisajadidi** [comment]
Don't send me any notification pleeeeease

**Comment by jhonatasobrinho** [comment]
No solutions found for this issue?

**Comment by ceefour** [comment]
@parisajadidi Rather than complaining to fellow users that have no access to your notification settings, would you take time to use the GitHub UI to unsubscribe?

![image](https://user-images.githubusercontent.com/24123/32763990-be3b4c40-c935-11e7-8d84-f9938e0ddcd4.png)

**Comment by horiuchie** [comment]
For Expo, I needed to replace `.hex` with `.hexString` in ejected theme.

Now, in Expo 23(latest version), color 2.0.1 will be installed in `node_modules` when initializing a project.

I will paste the outputs that I tried 'npm install --save color' in the following two cases.

Expo 22:
```
├─┬ color@2.0.1 
│ ├── color-convert@1.9.1 
│ └── color-string@1.5.2 
└─┬ expo@22.0.0
  ├── UNMET PEER DEPENDENCY react@>=15.4.0
  └─┬ react-native-svg@5.4.2
    └─┬ color@0.11.4 
      └── color-string@0.3.0 
```

Expo 23:
```
├─┬ color@2.0.1 
│ └─┬ color-string@1.5.2 
│   └─┬ simple-swizzle@0.2.2 
│     └── is-arrayish@0.3.1 
└─┬ expo@23.0.0
  ├── react-native-svg@5.5.1 
  └── websql@0.4.4 
```

So I have been using a ejected theme without replacing.

**Comment by SupriyaKalghatgi** [comment]
@horiuchie I am looking into this
Also i will upgrade this repo

**Comment by SupriyaKalghatgi** [comment]
Repo is upgraded, please refer branches `master` and `CRNA`

**Comment by NULL-SWEAT** [comment]
Getting this error on `2.4.5` after ejecting the theme. Replacing 'hex()' with 'hexString()' fixes.
Not using Expo.
