### ISSUE TITLE
Module progress bar doesn't exists

### ISSUE THREAD

**Issue by croustibat** [GeekyAnts/NativeBase-KitchenSink#22]
Hi,

I've got this error with progressbar.io.js module 

```
 UnableToResolveError: Unable to resolve module native-base/Components/Base/NativeBaseComponent from 

/Users/baptiste/Projects/Mobile/MATNOIRE/MNRN/NativeBase-KitchenSink/js/components/loaders/ProgressBar.ios.js: Module does not exist in the module map or in these directories:

  /Users/baptiste/Projects/Mobile/MATNOIRE/MNRN/NativeBase-KitchenSink/node_modules/native-base/Components/Base

,/Users/baptiste/node_modules/native-base/Components/Base

```
Actually the node_modules/native-base/Components doesn't exist at all. 

I've just removed all occurence of progressbar component in the app.js to make app works temporally, but can you explain me why the directory doesn't exist here ? did i forget something ?

Thank you.

**Comment by skeebuzz** [comment]
+1 RN 0.42.0-rc.3, native-base 2.0.7

**Comment by SupriyaKalghatgi** [comment]
@croustibat @skeebuzz Check with the latest release of NativeBase KitchenSink
