### ISSUE TITLE
Empty Optional cannot be unwrapped

### ISSUE THREAD

**Issue by marcalbet** [GeekyAnts/NativeBase-KitchenSink#26]
I am trying to run this app in a real android device but I get a red screen with this meesage: "Could not get BatchedBridge, make sure your bundle is pacckaged correctly" in the device.

I am executing the app through Android Studio IDE and grandle is compiled without problems. After the execution, I receive this message on console: 
"Caused by: java.lang.RuntimeException: Empty Optional cannot be unwrapped"

Thanks.

**Comment by SupriyaKalghatgi** [comment]
@marcalbet Did you try with the latest release of NativeBase KitchenSink?
