### ISSUE TITLE
Application not registered

### ISSUE THREAD

**Issue by niklasp** [GeekyAnts/NativeBase-KitchenSink#28]
Builds successful but when running on device or emulator:

> Application NativebaseKitchenSink has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
> runApplication
>     AppRegistry.js:99
> __callFunction
>     MessageQueue.js:236
> <unknown>
>     MessageQueue.js:108
> guard
>     MessageQueue.js:46
> callFunctionReturnFlushedQueue
>     MessageQueue.js:107
>

**Comment by SupriyaKalghatgi** [comment]
@niklasp This happens if you had an unsuccessful try for renaming the app
Or if any other project is running its packager.
You can terminate all the process from your terminal and try again
