### ISSUE TITLE
Can't ignore CodePush Deployment Key when executing react-native link

### ISSUE THREAD

**Issue by HermantoTang** [GeekyAnts/NativeBase-KitchenSink#29]
Got this error
```
$ react-native link
? What is your CodePush deployment key for Android (hit <ENTER> to ignore)
? What is your CodePush deployment key for Android (hit <ENTER> to ignore)
rnpm-install info Linking react-native-code-push android dependency
rnpm-install info Android module react-native-code-push has been successfully linked
rnpm-install info iOS module react-native-code-push is already linked
"CodePush.h" header already imported.
C:\Users\User8\desktop\KitchenSink\node_modules\react-native-code-push\scripts\postlink\ios\postlink.js:26
var oldJsCodeLocationAssignmentStatement = appDelegateContents.match(/(jsCodeLocation = .*)\n/)[1];
                                                                                               ^

TypeError: Cannot read property '1' of null
    at Object.<anonymous> (C:\Users\User8\desktop\KitchenSink\node_modules\react-native-code-push\scripts\postlink\ios\postlink.js:26:96)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User8\desktop\KitchenSink\node_modules\react-native-code-push\scripts\postlink\run.js:1:63)
    at Module._compile (module.js:570:32)
C:\Users\User8\desktop\KitchenSink\node_modules\react-native\local-cli\core\makeCommand.js:19
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (C:/Users/User8/desktop/KitchenSink/node_modules/react-native/local-cli/core/makeCommand.js:19:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

```

**Comment by shivrajkumar** [comment]
Give any string value when it asks for deployment key

**Comment by HermantoTang** [comment]
Already tried, still the same error

**Comment by shivrajkumar** [comment]
try upgrading the code push module to `1.17.0-beta`

**Comment by HermantoTang** [comment]
Ok, that fixed the problem in `react-native link`
But, I got this error when running `react-native run-android`

`Starting JS server...
Running C:\Users\User8\AppData\Local\Android\Sdk/platform-tools/adb -s 192.168.1
64.101:5555 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && gradlew.bat install
Debug...

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\User8\Desktop\KitchenSink\android\app\build.gradle' line: 1
02

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find property 'MYAPP_RELEASE_STORE_FILE' on SigningConfig_Decorated{
name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=nul
l, storeType=null}.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 8.963 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment.
Go to https://facebook.github.io/react-native/docs/getting-started.html
and check the Android tab for setup instructions.`

**Comment by SupriyaKalghatgi** [comment]
@HermantoTang Check #27 
https://github.com/GeekyAnts/NativeBase-KitchenSink/issues/27#issuecomment-281583850

**Comment by bluedusk** [comment]
@HermantoTang Hi, thanks for the reference. The link problem is ok now but I got same error when `react-native run-android`. Have you fixed this too?

**Comment by HermantoTang** [comment]
@bluedusk  What error did you get?
