### ISSUE TITLE
Swipe Right or Android BackButton

### ISSUE THREAD

**Issue by badjoras7** [GeekyAnts/NativeBase-KitchenSink#31]
Hello guys,

How can I disable this behaviour, when I'm sliding right or pressing on the BackAndroid button.

[https://youtu.be/xsNmMF3tFdg](https://youtu.be/xsNmMF3tFdg)

Many thanks!

**Comment by SupriyaKalghatgi** [comment]
@badjoras7 You can modify the transition effects may be
