### ISSUE TITLE
Initial installation problum

### ISSUE THREAD

**Issue by mohithp** [GeekyAnts/NativeBase-KitchenSink#33]
hai,
am using windows. When i run 'react-native link' command after downloading packages  its showing some errors.

$ react-native link
'yarn' is not recognized as an internal or external command,
operable program or batch file.
Scanning 736 folders for symlinks in C:\Mohith\Program\reactnative\NativeBase-KitchenSink\node_modules (143ms)
? What is your CodePush deployment key for Android (hit <ENTER> to ignore)
? What is your CodePush deployment key for Android (hit <ENTER> to ignore)
rnpm-install info Linking react-native-code-push android dependency
rnpm-install info Android module react-native-code-push has been successfully linked
rnpm-install ERR! It seems something went wrong while linking. Error: Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found.
Please file an issue here: https://github.com/facebook/react-native/issues

Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found.

how to fix it.

**Comment by SupriyaKalghatgi** [comment]
@mohithp Just to know that, have you tried simulating RN apps before this?

**Comment by kukuandroid** [comment]
Hi, thank you..solve it already
