### ISSUE TITLE
Runs fine for Android, fails with iOS

### ISSUE THREAD

**Issue by pkassonss** [GeekyAnts/NativeBase-KitchenSink#34]
Here is the output from the CLI invocation of run-ios:

In file included from /Users/pkasson/Downloads/NativeBase-KitchenSink-master-2/ios/NativebaseKitchenSink/AppDelegate.m:11:
../node_modules/react-native-code-push/ios/CodePush/CodePush.h:1:9: fatal error: 'RCTEventEmitter.h' file not found
#import "RCTEventEmitter.h"
        ^
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC build/Build/Intermediates/NativebaseKitchenSink.build/Debug-iphonesimulator/NativebaseKitchenSink.build/Objects-normal/x86_64/AppDelegate.o NativebaseKitchenSink/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/NativebaseKitchenSink.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/NativebaseKitchenSink.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by obykoo** [comment]
Using with exponent , it lags sp much and opening swipable tabs make application crash

**Comment by pkassonss** [comment]
how does that affect the problem I am having at just getting it to build ?

**Comment by SupriyaKalghatgi** [comment]
@pkassonss I checked on branch **master**, [CFBundleIdentifier](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/ios/NativebaseKitchenSink/Info.plist#L9) does exist with Info.plist.
Could you check if its included in your Info.plist?

**Comment by pkassonss** [comment]
Its there, not sure why running from command line is producing this error, but its also producing those below.  It is clear that the path is off, inside Xcode the header search path is set to ../node_modules and subdirectories within, but looking at this path, it does not reference ../node_modules, thus it will of course fail, and I assume the Info.plist is just a false negative.

clang: error: no such file or directory: '/Users/pkasson/dev/ios/React/r_and_d/native-starter-kitchensink/NativeBase-KitchenSink/ios/RCTSettingsManager.m'
clang: error: no input files



** BUILD FAILED **


The following build commands failed:

	CompileC build/Build/Intermediates/RCTSettings.build/Debug-iphonesimulator/RCTSettings.build/Objects-normal/x86_64/RCTSettingsManager.o RCTSettingsManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/RCTSettings.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RCTSettings.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by SupriyaKalghatgi** [comment]
@pkassonss Can I know version of Xcode installed at your side?

**Comment by pkassonss** [comment]
Version 8.2.1 (8C1002)

**Comment by SupriyaKalghatgi** [comment]
@pkassonss Try clearing `node_modules` and install again

**Comment by pkassonss** [comment]
same result

**Comment by SupriyaKalghatgi** [comment]
@pkassonss Thats strange.

We have thousands of users using NativeBase KitchenSink; works smooth

**Comment by pkassonss** [comment]
I will pull down the latest and try it again

**Comment by SupriyaKalghatgi** [comment]
@pkassonss Any luck?

**Comment by pkassonss** [comment]
Sorry, will do a pull this morning and let you know !

**Comment by pkassonss** [comment]
Got new clone ... then:

npm install
npm install --save react-native@0.42
npm i whatwg-fetch@^1.0.0 --save
react-native link

react-native run-ios ... then:

../../react-native/React/Modules/RCTEventEmitter.h:10:9: fatal error: 'React/RCTBridge.h' file not found
#import <React/RCTBridge.h>

among other errors.

now, inside Xcode, there are several header files not found ... 

My assumption is something during the initial setup is missing, as headers are not found, both in Xcode and command line.

**Comment by iamraphson** [comment]
Having same error too @pkassonss @SupriyaKalghatgi 
<img width="271" alt="screen shot 2017-03-29 at 19 44 48" src="https://cloud.githubusercontent.com/assets/3502724/24470845/37027078-14b8-11e7-9c98-93fc713fff30.png">

**Comment by pkassonss** [comment]
Glad to see someone else is having this issue (sorry iamraphson), but I keep seeing this issue whereas it seemed I was only one.

**Comment by shivrajkumar** [comment]
@pkassonss If you are changing the RN version, you need to upgrade native code too.
You can do that with `react-native upgrade`.
Also you will need to upgrade the version of `react-native-code-push` to latest.

**Comment by shivrajkumar** [comment]
@pkassonss @iamraphson We have upgraded the app for RN `0.42.3` though now.
So you can pull the latest.

**Comment by pkassonss** [comment]
Ah, that makes more sense now.  Thanks, I will try it.

**Comment by pkassonss** [comment]
Thanks Shiva ... it worked !
