### ISSUE TITLE
open a page from sidebar seems not smooth ?

### ISSUE THREAD

**Issue by justmao945** [GeekyAnts/NativeBase-KitchenSink#36]
When I try to open a page from the sidebar, it will block about 200~300ms before show the content. So is it a problem in the real app if I use native base or can be optimized ? I'm new to react native, please correct me if I'm wrong. Thank you.

**Comment by SupriyaKalghatgi** [comment]
@justmao945 NativeBase is working on optimizing.
So far NativeBase has cut down the lag by more than half.
Keep waiting
