### ISSUE TITLE
Facing issues while setting up local debugging server for remote-dev-tools-on-debugger

### ISSUE THREAD

**Issue by hussainb** [GeekyAnts/NativeBase-KitchenSink#39]
Following the guide on [remote-redux-devtools-on-debugger](https://github.com/jhen0409/remote-redux-devtools-on-debugger#install-dev-dependencies)

after updating the following section with 
```

"scripts": {
  "postinstall": "remotedev-debugger --hostname localhost --port 5678 --injectserver"
}
```

the command `react-native start` fails with error:
`NativeBase-KitchenSink-master/node_modules/react-native/local-cli/server/server.js: Unexpected token (2:1)`

**Comment by GeekRishabh** [comment]
@hussainb Follow up the documentation [here](https://github.com/jhen0409/remote-redux-devtools-on-debugger) .Will work for you

**Comment by SupriyaKalghatgi** [comment]
@hussainb Sorry for delayed response

Let us know if you need help on this

**Comment by hussainb** [comment]
Hi, I switched to ionic 2 due to lack of documentation, support and pre made layouts/themes in the react native ecosystem.
