### ISSUE TITLE
Issue with Button under FooterTab

### ISSUE THREAD

**Issue by zurodtl** [GeekyAnts/NativeBase-KitchenSink#4]
The onPress action of Button under FooterTab is not working. I've tried a Button under Footer tag without FooterTab, it works.

**Comment by SupriyaKalghatgi** [comment]
This has been added with 0.5.11 release of NativeBase.
Check this
![ref-1](https://cloud.githubusercontent.com/assets/13464885/19636844/5f98f236-99e9-11e6-9e61-d997d899ed6d.gif)

**Comment by SupriyaKalghatgi** [comment]
@zurodtl Did you get it working?

**Comment by SupriyaKalghatgi** [comment]
@zurodtl Check the latest release of NativeBase KitchenSink

**Comment by SupriyaKalghatgi** [comment]
Fixed with [0.5.13](https://github.com/GeekyAnts/NativeBase-KitchenSink/releases/tag/0.5.13)
