### ISSUE TITLE
unable to deploy on android

### ISSUE THREAD

**Issue by antonioaltamura** [GeekyAnts/NativeBase-KitchenSink#41]
Hi, I'm new to react-native, I'm trying to explore its potentiality.
I tried to deploy this demo app on (Samsung A300FU - android 6.0.1) but I get this error.
I tried to clear the cache as the error suggests, I didn't solve.

![react-error](https://cloud.githubusercontent.com/assets/6325475/25052048/1d831928-2150-11e7-8eb3-b8195d53a23c.jpg)

**Comment by vu-le** [comment]
Having the same error with Samsung S4 Android 5.1

**Comment by cstd** [comment]
yarn add native-base@2.1.0 will solve this problem

**Comment by antonioaltamura** [comment]
it solved for me
