### ISSUE TITLE
Can't get it working on iOS

### ISSUE THREAD

**Issue by zmijat** [GeekyAnts/NativeBase-KitchenSink#42]
Using the latest: be9f9b6ddf92a33b4cc1741bbebbb8caffd901d3

npm v3.10.10
node v6.10.2
react@15.4.2
react-native@0.42.3
native-base@2.1.1

Installing as per README. After running `react-native run-ios`, project is built, but there is an error while bundling:

```
Loading dependency graph, done.
Bundling `index.ios.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░  93.1% (993/1033)...(node:38231) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2973): UnableToResolveError: Unable to resolve module `native-base-shoutem-theme` from `/Users/zoran/tmp/NativeBase-KitchenSink/node_modules/native-base/dist/src/basic/CardItem.js`: Module does not exist in the module map or in these directories:
  /Users/zoran/tmp/NativeBase-KitchenSink/node_modules/native-base/node_modules
,   /Users/zoran/tmp/NativeBase-KitchenSink/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
Bundling `index.ios.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░  99.4% (1054/1057)...

```

App is run anyway. Note that Transforming modules is stuck on 99.4%. 

In Simulator (iOS 10.3 iPhone 6s), getting the same error, with additional step to try (resetting packager cache).

![screen shot 2017-04-15 at 18 17 39](https://cloud.githubusercontent.com/assets/7346693/25074903/5f52ae98-22dd-11e7-9247-c7f2374e1515.png)

Tried everything several times, but no luck.

**Comment by stranger26** [comment]
It worked for me after changing the react version
`"react": "16.0.0-alpha.6",
    "react-native": "0.43.0"`

**Comment by zmijat** [comment]
Thanks @stranger26, that did the trick.
