### ISSUE TITLE
Issues with starting up the NativeBase-KitchenSink Project

### ISSUE THREAD

**Issue by ReactBeginner** [GeekyAnts/NativeBase-KitchenSink#43]
Hello, having issues starting up the NativeBase-KitchenSink Project in React Native

I keep receiving the following error

The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false

Body:
{"from":"C:\\Users\\Martin\\Documents\\React JS\\NativeBase-KitchenSink\\node_modules\\native-base\\dist\\src\\basic\\Tabs\\SceneComponent.js","to":"react-native/Libraries/Components/StaticContainer.react","message":"Unable to resolve module `react-native/Libraries/Components/StaticContainer.react` from `C:\\Users\\Martin\\Documents\\React JS\\NativeBase-KitchenSink\\node_modules\\native-base\\dist\\src\\basic\\Tabs\\SceneComponent.js`: Module does not exist in the module map or in these directories:\n  C:\\Users\\Martin\\Documents\\React JS\\NativeBase-KitchenSink\\node_modules\\native-base\\node_modules\\react-native\\Libraries\\Components\n,   C:\\Users\\Martin\\Documents\\React JS\\NativeBase-KitchenSink\\node_modules\\react-native\\Libraries\\Components\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}
onResponse
    DevServerHelper.java:339
execute
    RealCall.java:126
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1133
run
    ThreadPoolExecutor.java:607
run
    Thread.java:761

My package file is as follows

{
  "name": "NativebaseKitchenSink",
  "version": "2.0.0",
  "private": true,
  "scripts": {
    "postinstall": "remotedev-debugger",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "eslint": "eslint",
    "test": "jest",
    "eject-native-base": "node node_modules/native-base/ejectTheme.js"
  },
  "dependencies": {
    "color": "0.11.1",
    "lodash": "4.13.1",
    "moment": "2.13.0",
    "native-base": "https://github.com/GeekyAnts/NativeBase#master",
    "react": "15.4.2",
    "react-native": "0.42.3",
    "react-native-code-push": "1.17.0-beta",
    "react-native-easy-grid": "0.1.8",
    "react-native-modalbox": "1.3.4",
    "react-native-navigation-redux-helpers": "0.5.0",
    "react-native-router-flux": "3.37.0",
    "react-native-scrollable-tab-view": "0.6.0",
    "react-redux": "4.4.5",
    "redux": "3.5.2",
    "redux-form": "6.2.0",
    "redux-persist": "3.2.2",
    "redux-thunk": "2.1.0",
    "remote-redux-devtools": "0.3.3",
    "whatwg-fetch": "1.0.0"
  },
  "devDependencies": {
    "babel-eslint": "6.1.2",
    "babel-jest": "16.0.0",
    "babel-preset-react-native": "1.9.0",
    "chai": "3.5.0",
    "eslint": "3.5.0",
    "eslint-config-airbnb": "11.1.0",
    "eslint-plugin-import": "1.14.0",
    "eslint-plugin-jsx-a11y": "2.2.1",
    "eslint-plugin-react": "6.2.0",
    "eslint-plugin-react-native": "2.0.0",
    "jest": "16.0.2",
    "jest-react-native": "16.1.0",
    "mocha": "2.5.3",
    "react-test-renderer": "15.4.2",
    "remote-redux-devtools-on-debugger": "0.4.6",
    "remotedev-server": "0.1.2"
  },

What am I doing incorrectly?  Please bear with me as I am new to react-native and nativebase.

**Comment by thumarmahesh** [comment]
This app has no updated dependecis. As a work around put
```
-    "react": "15.4.2",
-    "react-native": "0.42.3",
+    "react": "16.0.0-alpha.6",
+    "react-native": "0.43.0",
``` 
in your package.json and rund `npm install`

**Comment by ReactBeginner** [comment]
Thanks Thumarmahesh,

I have now attempted to build the project and receive the following error

C:\Users\Martin\Documents\React JS\NativeBase-KitchenSink\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:22: error: cannot find symbol
import com.facebook.react.uimanager.ReactChoreographer;
                                   ^
  symbol:   class ReactChoreographer
  location: package com.facebook.react.uimanager
C:\Users\Martin\Documents\React JS\NativeBase-KitchenSink\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:257: error: package ReactChoreographer does not exist
                                    ReactChoreographer.getInstance().postFrameCallback(ReactChoreographer.CallbackType.TIMERS_EVENTS, new Choreographer.FrameCallback() {
                                                                                                         ^
C:\Users\Martin\Documents\React JS\NativeBase-KitchenSink\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:257: error: cannot find symbol
                                    ReactChoreographer.getInstance().postFrameCallback(ReactChoreographer.CallbackType.TIMERS_EVENTS, new Choreographer.FrameCallback() {
                                    ^
  symbol: variable ReactChoreographer
3 errors
:react-native-code-push:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-code-push:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.62 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by unitedhotdog** [comment]
Same Errors for original package.json & alt package.json

**Comment by ReactBeginner** [comment]
The issue appears to lie with 'react-native-code-push', would anyone know which version of this module is compatible with the following versions of react & react-native (see below)

"react": "16.0.0-alpha.6",
"react-native": "0.43.0",

Perhaps I have missed something here, but it seems like all react-native native-base projects seem to suffer from dependency conflicts.

**Comment by ssteffann** [comment]
@ReactBeginner  for me worked to change `package.json` to this
```javascript
"react": "16.0.0-alpha.3",
    "react-native": "0.43.1",
    "react-native-code-push": "2.0.1-beta",
```
as example i took `package.json` from https://github.com/start-react/native-starter-kit

**Comment by thomasmktong** [comment]
@ssteffann your changes work for me, thanks.

**Comment by ReactBeginner** [comment]
Unfortunately that change still did not work for me..  I still keep receiving issues related to 'react-native-code-push'

PS C:\Users\Martin\Documents\React JS\NativeBase-KitchenSink> react-native run-android
'yarn' is not recognized as an internal or external command,
operable program or batch file.
Scanning 745 folders for symlinks in C:\Users\Martin\Documents\React JS\NativeBase-KitchenSink\node_modules (18ms)
JS server already running.
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-code-push:preBuild UP-TO-DATE
:react-native-code-push:preReleaseBuild UP-TO-DATE
:react-native-code-push:checkReleaseManifest
:react-native-code-push:preDebugAndroidTestBuild UP-TO-DATE
:react-native-code-push:preDebugBuild UP-TO-DATE
:react-native-code-push:preDebugUnitTestBuild UP-TO-DATE
:react-native-code-push:preReleaseUnitTestBuild UP-TO-DATE
:react-native-code-push:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-code-push:prepareComAndroidSupportRecyclerviewV72340Library UP-TO-DATE
:react-native-code-push:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:react-native-code-push:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
:react-native-code-push:prepareComFacebookFrescoDrawee101Library UP-TO-DATE
:react-native-code-push:prepareComFacebookFrescoFbcore101Library UP-TO-DATE
:react-native-code-push:prepareComFacebookFrescoFresco101Library UP-TO-DATE
:react-native-code-push:prepareComFacebookFrescoImagepipeline101Library UP-TO-DATE
:react-native-code-push:prepareComFacebookFrescoImagepipelineBase101Library UP-TO-DATE
:react-native-code-push:prepareComFacebookFrescoImagepipelineOkhttp3101Library UP-TO-DATE
:react-native-code-push:prepareComFacebookReactReactNative0431Library UP-TO-DATE
:react-native-code-push:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-code-push:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-code-push:prepareReleaseDependencies
:react-native-code-push:compileReleaseAidl UP-TO-DATE
:react-native-code-push:compileReleaseNdk UP-TO-DATE
:react-native-code-push:compileLint UP-TO-DATE
:react-native-code-push:copyReleaseLint UP-TO-DATE
:react-native-code-push:compileReleaseRenderscript UP-TO-DATE
:react-native-code-push:generateReleaseBuildConfig UP-TO-DATE
:react-native-code-push:generateReleaseResValues UP-TO-DATE
:react-native-code-push:generateReleaseResources UP-TO-DATE
:react-native-code-push:mergeReleaseResources UP-TO-DATE
:react-native-code-push:processReleaseManifest UP-TO-DATE
:react-native-code-push:processReleaseResources UP-TO-DATE
:react-native-code-push:generateReleaseSources UP-TO-DATE
:react-native-code-push:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:react-native-code-push:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-code-push:extractReleaseAnnotations UP-TO-DATE
:react-native-code-push:mergeReleaseShaders UP-TO-DATE
:react-native-code-push:compileReleaseShaders UP-TO-DATE
:react-native-code-push:generateReleaseAssets UP-TO-DATE
:react-native-code-push:mergeReleaseAssets UP-TO-DATE
:react-native-code-push:mergeReleaseProguardFiles UP-TO-DATE
:react-native-code-push:packageReleaseRenderscript UP-TO-DATE
:react-native-code-push:packageReleaseResources UP-TO-DATE
:react-native-code-push:processReleaseJavaRes UP-TO-DATE
:react-native-code-push:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:react-native-code-push:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:react-native-code-push:mergeReleaseJniLibFolders UP-TO-DATE
:react-native-code-push:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:react-native-code-push:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:react-native-code-push:bundleRelease UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72340Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee101Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore101Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco101Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline101Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase101Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp3101Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0431Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareNativebaseKitchenSinkReactNativeCodePushUnspecifiedLibrary
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources

FAILURE: Build failed with an exception.

* What went wrong:
Could not read path 'C:\Users\Martin\Documents\React JS\NativeBase-KitchenSink\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-af'.
> C:\Users\Martin\Documents\React JS\NativeBase-KitchenSink\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-af

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.745 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:

In the alternate powershell window I have the following error 

PS C:\Users\Martin\Documents\React JS\NativeBase-KitchenSink> react-native start
'yarn' is not recognized as an internal or external command,
operable program or batch file.
Scanning 745 folders for symlinks in C:\Users\Martin\Documents\React JS\NativeBase-KitchenSink\node_modules (19ms)
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   C:\Users\Martin\Documents\React JS\NativeBase-KitchenSink

Loading dependency graph...
React packager ready.

Loading dependency graph, done.
 ERROR  EPERM: operation not permitted, lstat 'C:\Users\Martin\Documents\React JS\NativeBase-KitchenSink\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values'
{"errno":-4048,"code":"EPERM","syscall":"lstat","path":"C:\\Users\\Martin\\Documents\\React JS\\NativeBase-KitchenSink\\android\\app\\build\\intermediates\\incremental\\mergeDebugResources\\merged.
dir\\values"}
Error: EPERM: operation not permitted, lstat 'C:\Users\Martin\Documents\React JS\NativeBase-KitchenSink\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values'
    at Error (native)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
PS C:\Users\Martin\Documents\React JS\NativeBase-KitchenSink>

This appears to be a permissions error, but I have opened up file under 'React JS' to Full.

**Comment by ReactBeginner** [comment]
Managed to resolve the remaining issues on my own, but thanks @thumarmahesh and @ssteffann for the pointers re dependency setup..

**Comment by dominicsavb** [comment]
how to resolve this? 

Thank you

**Comment by zkrige** [comment]
@martinikediashi how did you resolve?

**Comment by SupriyaKalghatgi** [comment]
Facing this issue with latest update?

**Comment by moeraad** [comment]
@SupriyaKalghatgi  yes i just download it and followed the steps but got the below message when trying to link the vectors library
`import type {CommandT} from './commands';

^^^^^^`
