### ISSUE TITLE
"react-native start" is crashing

### ISSUE THREAD

**Issue by surikat** [GeekyAnts/NativeBase-KitchenSink#44]
Hello,
first I want to thank you for this great tool you made (native-base),

I'm on node v7.8.0

I have a problem to launch the "react-native start" command after the init steps:

jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /var/www/NativeBase-KitchenSink/node_modules/react-native/package.json collides with /var/www/NativeBase-KitchenSink/node_modules/react-native-router-flux/node_modules/react-native/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /var/www/NativeBase-KitchenSink/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /var/www/NativeBase-KitchenSink/node_modules/react-native-router-flux/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /var/www/NativeBase-KitchenSink/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /var/www/NativeBase-KitchenSink/node_modules/react-native-router-flux/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/var/www/NativeBase-KitchenSink/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/var/www/NativeBase-KitchenSink/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)

**Comment by jsina** [comment]
same here...

**Comment by ferdingler** [comment]
same

**Comment by rafmsou** [comment]
+1

**Comment by shivrajkumar** [comment]
#45
