### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by alexaung** [GeekyAnts/NativeBase-KitchenSink#45]
I have downloaded NativeBase-KitchenSink and try to build but I got the following error. Here is my installation step -:

npm install
react-native link
react-native start
Then got the following error.

Failed to build DependencyGraph: @providesModule naming collision:
Duplicate module name: react-native
Paths: C:\My App\ReactNative\ReactJs\NativeBase-KitchenSink-master\node_modules\react-native-router-flux
\node_modules\react-native\package.json collides with C:\My App\ReactNative\ReactJs\NativeBase-KitchenSink
-master\node_modules\react-native\package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
Duplicate module name: react-native
Paths: C:\My App\ReactNative\ReactJs\NativeBase-KitchenSink-master\node_modules\react-native-router-flux
\node_modules\react-native\package.json collides with C:\My App\ReactNative\ReactJs\NativeBase-KitchenSink
-master\node_modules\react-native\package.json

This error is caused by a @providesModule declaration with the same name across two different files.
at HasteMap.updateHasteMap (C:/My App/ReactNative/ReactJs/NativeBase-KitchenSink-master/nodemodules/
react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
at p.getName.then.name (C:/My App/ReactNative/ReactJs/NativeBase-KitchenSink-master/node_modules/react
-native/packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)

**Comment by shivrajkumar** [comment]
@alexaung The issue seems to be with the latest version of  `react-native-router-flux` v3.38.1. You can just downgrade it to v3.37.0 or v3.38.0 and try

**Comment by alexaung** [comment]
Actuall, I did ran on v3.37.0. Please see my dependencies. I did change nothing.

"dependencies": {
    "color": "~0.11.1",
    "lodash": "^4.13.1",
    "moment": "^2.13.0",
    "native-base": "https://github.com/GeekyAnts/NativeBase#master",
    "react": "15.4.2",
    "react-native": "0.42.3",
    "react-native-code-push": "1.17.0-beta",
    "react-native-easy-grid": "^0.1.8",
    "react-native-modalbox": "^1.3.4",
    "react-native-navigation-redux-helpers": "^0.5.0",
    "react-native-router-flux": "^3.37.0",
    "react-native-scrollable-tab-view": "^0.6.0",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-form": "^6.2.0",
    "redux-persist": "^3.2.2",
    "redux-thunk": "^2.1.0",
    "remote-redux-devtools": "^0.3.3"
  },

**Comment by alexaung** [comment]
If I install 3.38.0, I got the following error during the installation.

C:\My App\ReactNative\ReactJs\dicalaws>npm install --save react-native-router-flux@3.38.0
dicalaws@0.0.1 C:\My App\ReactNative\ReactJs\dicalaws
`-- react-native-tabs@1.0.9  extraneous

npm WARN @shoutem/animation@0.8.10 requires a peer of react@^15.0.0 but none was installed.
npm WARN native-base-shoutem-theme@0.1.0 requires a peer of react@>=15.1.0 but none was installed.
npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.
npm ERR! path C:\My App\ReactNative\ReactJs\dicalaws\node_modules\.staging\react-native-experimental-navigation-e2c6a3e5
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\My App\ReactNative\ReactJs\dicalaws\node_modules\.staging\react-native-experimental-navigation-e2c6a3e5' -> 'C:\My App\ReactNative\ReactJs\dicalaws\node_modules\react-native-experimental-navigation'
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\My App\ReactNative\ReactJs\dicalaws\node_modules\.staging\react-native-experimental-navigation-e2c6a3e5' -> 'C:\My App\ReactNative\ReactJs\dicalaws\node_modules\react-native-experimental-navigation'
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\My App\\ReactNative\\ReactJs\\dicalaws\\node_modules\\.staging\\react-native-experimental-navigation-e2c6a3e5',
npm ERR!   dest: 'C:\\My App\\ReactNative\\ReactJs\\dicalaws\\node_modules\\react-native-experimental-navigation',
npm ERR!   parent: 'dicalaws' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Swordfish\AppData\Roaming\npm-cache\_logs\2017-04-26T09_35_30_021Z-debug.log

**Comment by shivrajkumar** [comment]
@alexaung remove `^` from "react-native-router-flux": "^3.37.0"

**Comment by alexaung** [comment]
Thanks shivra. It is working now. I will try to setup new project with latest react-native version.
