### ISSUE TITLE
change project name

### ISSUE THREAD

**Issue by slimeygecko** [GeekyAnts/NativeBase-KitchenSink#46]
what are your recommendations on how to change the name of the application?

**Comment by shivrajkumar** [comment]
@slimeygecko http://blog.tylerbuchea.com/renaming-a-react-native-project/

**Comment by GeekRishabh** [comment]
@slimeygecko  If you are using CRNA branch code then you need to change App name in Package.json and in App.json . (slug & Name) .

**Comment by slimeygecko** [comment]
thanks guys! I also ran across this project which seems promising (and potentially less manual file modifying): https://github.com/junedomingo/react-native-rename
