### ISSUE TITLE
Search bar text width unusably narrow

### ISSUE THREAD

**Issue by cfedk** [GeekyAnts/NativeBase-KitchenSink#48]
Out of the box, I get the following in the "search bar" section, both using an emulator and on a physical device. 

![image](https://cloud.githubusercontent.com/assets/1285997/25585786/2f3d5f7e-2e94-11e7-8bd6-e8bc187e3c77.png)

As far as I am concerned, the input item should use as much horizontal width as it can...

**Comment by GeekRishabh** [comment]
@cfedk seems to work fine . Please share the code snippet/repo url along with the RN,NB version you are using so that we can help you out .

**Comment by brodus13** [comment]
I'm actually also having this issue. Not only here, but in the example for Form & Inputs > Any textbox

This is happening on 2 Android devices I installed it on as well as the emulator.

![brokentextbox](https://cloud.githubusercontent.com/assets/11520122/25620033/5db75028-2f23-11e7-8c9a-8f7201cc86ae.png)

**Comment by GeekRishabh** [comment]
@brodus13 which branch you are using ??

**Comment by brodus13** [comment]
What brand device? One is a Google Pixel, the other is an LG G5

**Comment by GeekRishabh** [comment]
@brodus13 which branch of this repo you are using ?

**Comment by brodus13** [comment]
Master

**Comment by GeekRishabh** [comment]
@brodus13 try using CRNA branch

**Comment by brodus13** [comment]
Cool, I will do that as soon as I get home (in about 6 hours from now) and I'll come back here to let you know if that worked. Really appericiate the quick replies 👍 😄

**Comment by brodus13** [comment]
Unfortunately this did not fix it.

**Comment by brodus13** [comment]
Scratch that, I thought I was on that branch but I was still on master. I had trouble using the CRNA branch, as I couldn't quite figure out the setup, it wasn't as simple as the master branch, without an android folder and whatnot.

**Comment by dobrienlzd** [comment]
I am seeing the same issue running the Kitchen Sink App Nexus_5X_API_25 emulator! What's going on guys?

**Comment by GeekRishabh** [comment]
@brodus13 @dobrienlzd fixed it guys .Try again .

**Comment by cfedk** [comment]
Fixed for me.
