### ISSUE TITLE
Keyboard gets closed when navigating from one input to another

### ISSUE THREAD

**Issue by sagark1510** [GeekyAnts/NativeBase-KitchenSink#5]
Hi,

I am working on login screen. Input component works fine but when I tap on username Input and navigate to password input field keyboard gets closed. 

Is this because Content component has scrollview though its my assumption as I have not tried it yet.

**Comment by SupriyaKalghatgi** [comment]
[#243](https://github.com/GeekyAnts/NativeBase/issues/243)
