### ISSUE TITLE
Update NativeBase-KitchenSink

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [GeekyAnts/NativeBase-KitchenSink#54]
- [x] Restore Router Flux to a branch
- [x] Upgrade to RN 45 and NB 2.1.5 on `master`
- [x] Clean code
- [x] ReadMe for `master`, `router-flux`, `CRNA`

**Comment by Bombe93** [comment]
I was just thinking about seeing if someone had written something.
In recent days I tried to upgrade to the higher versions of React Native and I found some problems with navigation that was revised.
Hope it will become compatible, it's very useful. 
Thank you

**Comment by SupriyaKalghatgi** [comment]
@Bombe93 You can check branch `react-navigation` (CRNA app) for latest RN and NativeBase with react-navigation

**Comment by Bombe93** [comment]
I'm using redux and updating to the latest version I had a problem with navigation.
(NavigationExperimental and NavigationCardStack)
Following the changes of the branch NBv2.1.5 I was able to work with React Native 0.44.0.
Thanks

**Comment by SupriyaKalghatgi** [comment]
@Bombe93 Good to know that

**Comment by myerzman** [comment]
Sorry, I'm a novice. I did a git clone, and an install.. all looks good. started project. It's running on Port 8081. Dependency graphy loaded done... but I don't see any QR code or URL for running in the expo app.? How do I view in expo app?

**Comment by SupriyaKalghatgi** [comment]
@myerzman You need to switch to CRNA branch for that

**Comment by SupriyaKalghatgi** [comment]
NativeBase-KitchenSink updated as per checklist in issue definition
