### ISSUE TITLE
Unable to build example :( Out of sync

### ISSUE THREAD

**Issue by hgonzalez94** [GeekyAnts/NativeBase-KitchenSink#58]
![image](https://user-images.githubusercontent.com/6015420/27721365-abe4489a-5d14-11e7-84c7-2cce330ea122.png)
just used default steps.

**Comment by SupriyaKalghatgi** [comment]
@hgonzalez94 Please share the steps you followed

**Comment by SupriyaKalghatgi** [comment]
@hgonzalez94 Any updates?
