### ISSUE TITLE
Please add FAB component

### ISSUE THREAD

**Issue by lucianomlima** [GeekyAnts/NativeBase-KitchenSink#6]
In the NativeBase docs, don't have an example and in KitchenSink app don't have too.

**Comment by SupriyaKalghatgi** [comment]
@lucianomlima Did you check the latest [docs](http://nativebase.io/docs/v0.5.13/components#fab) of NativeBase?

**Comment by lucianomlima** [comment]
Yes, but here in KitchenSink don't have the Fab component.

**Comment by SupriyaKalghatgi** [comment]
@lucianomlima Yes we will be adding it very soon

**Comment by lucianomlima** [comment]
👍

**Comment by SupriyaKalghatgi** [comment]
Added FAB
