### ISSUE TITLE
Unable to close drawer when a scene is changed from selection in drawer

### ISSUE THREAD

**Issue by darren1982** [GeekyAnts/NativeBase-KitchenSink#63]
I ran the the default example of the library. The drawer is able to show and tap on it will open the correct screen. However, when tap on the item, the screen is loaded on the background but the drawer itself does not close. I need to tap outside of the drawer, then only the drawer will be closed and see the screen loaded behind. 

Is there anything I can do to hide the drawer automatically whenever user tap on the item? 

I notice the code in sidebar.index.js. It seems like already done that. It called the closeDrawer(). But the drawer doesnt close. I tried to add closeDrawer() to my screen didMount() but it doenst close either

<ListItem
                                button
                                noBorder
                                onPress={() => {
                                    console.log("menu item pressed.");
                                    Actions[data.route]();
                                    this.props.closeDrawer();
                                }}
                            >

![image](https://user-images.githubusercontent.com/1927976/28505790-57da20a0-7059-11e7-85c9-5b2f344227f2.png)

**Comment by amorenew** [comment]
by default in android or ios side bar should be closed after selection

**Comment by amorenew** [comment]
Solved by
`< SideBar closeDrawer={()=>this.closeDrawer()}/>}>
`
then on item click in the SideBar
I call
`this.props.closeDrawer();`
