### ISSUE TITLE
2 warnings in 2.2.1 (WIN10)

### ISSUE THREAD

**Issue by j2l** [GeekyAnts/NativeBase-KitchenSink#65]
Just 2 warnings (2.2.1? @SupriyaKalghatgi):
![screenshot_2017-07-26-13-50-13](https://user-images.githubusercontent.com/65325/28619648-aa37166c-7209-11e7-8043-a2115c435b22.png)

Is it fixed in 2.3.0?

**Comment by SupriyaKalghatgi** [comment]
Upgrading to RN 47 and Expo 20 removes these warnings
