### ISSUE TITLE
Dragging on an Input shows keyboard on next tab page

### ISSUE THREAD

**Issue by Shu-Ji** [GeekyAnts/NativeBase-KitchenSink#67]
I'm using tabs component.

After cloning the latest KitchenSink code, I add one line in the source code as below:

file: [js/components/tab/tabOne.js#line30](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/tab/tabOne.js#L30)

```jsx
// add one Input component after the <Card>...</Card> component: 
    ...
    <Input placeholder="this is an Input component" style={{height: 50, borderWidth: 1}} />
</Content>
```

Then, if I drag on this input, then keyboard shows in the next tab content, which shouldn't be.

This only happens on iOS, but Android is OK, the keyboard will not show.

screenshot below:

![ios](https://user-images.githubusercontent.com/1127594/28993959-f714c2ac-79f4-11e7-8c20-6d22450fe22c.gif)

**Comment by SupriyaKalghatgi** [comment]
@Shu-Ji I think, dragging on an Input is nothing but clicking on it, which gets into focus

**Comment by Shu-Ji** [comment]
@SupriyaKalghatgi  So, android will eat 'click' event when 'dragging' the input?

**Comment by SupriyaKalghatgi** [comment]
yes

**Comment by Shu-Ji** [comment]
Is there any way to make iOS work like android?

**Comment by SupriyaKalghatgi** [comment]
There is no work around this
