### ISSUE TITLE
Floating Label android 4.4.2 issue

### ISSUE THREAD

**Issue by clarktank** [GeekyAnts/NativeBase-KitchenSink#69]
Hi Thanks for a great product. I am filing this issue to make the product better.
I have 4.4.2 android tablet and have the following issues when I go to your Kitchen-sink app -> Form & Inputs -> Floating Label

1. The first letter of the username is not shown properly.
2. Password is not protected.
3. the header doesn't have a margin-top and collides with status bar.
4. the divider line extends all the the way to the left with no left margin.

![img_1963](https://user-images.githubusercontent.com/31081495/29388352-5cde3b7a-82b2-11e7-9c5e-c38d307f099a.jpg)

**Comment by SupriyaKalghatgi** [comment]
>The first letter of the username is not shown properly.

Can you check the same from branch `master`?

**Comment by clarktank** [comment]
Thanks for the reply, I open expo app on my tablet using this link exp://exp.host/@geekyants/nativebasekitchensink.

**Comment by SupriyaKalghatgi** [comment]
@clarktank Yes by looking at the screenshot i know that you are checking this app from expo
I asked you to check from branch `master` and run it once
This is not related to NativeBase or NativeBase-KitchenSink

**Comment by clarktank** [comment]
I don't know how to do that?

**Comment by clarktank** [comment]
Do you mean to clone the app from the master branch on my local machine, and then use the android studio or android 4.4.2 emulator and see if I get the same results?

**Comment by SupriyaKalghatgi** [comment]
yes

**Comment by SupriyaKalghatgi** [comment]
You can check NativeBase KitchenSink from Play Store instead

**Comment by SupriyaKalghatgi** [comment]
@clarktank https://play.google.com/store/apps/details?id=io.market.nativebase.geekyants.nativebasekitchensink

**Comment by clarktank** [comment]
I installed the app on my android tablet. Thanks for the quick fix. The problem 1, 2 and 3 are solved except problem 4. The divider line extends all the the way to the left with no left margin.

**Comment by SupriyaKalghatgi** [comment]
@clarktank There wasn't any fix
Problem 1 and 3 is due to expo and not related to app
Problem 4 is not an issue, infact thats the UI design
