### ISSUE TITLE
Unhandled JS Exception: Invariant Violation 

### ISSUE THREAD

**Issue by Xurma2** [GeekyAnts/NativeBase-KitchenSink#7]
IOS

**Comment by jgknott** [comment]
I had the same issue on a fresh install.. Oddly enough, a reboot fixed it.  I think it had something to do with all the packages and new libs I was installing.

**Comment by SupriyaKalghatgi** [comment]
Restarting packager solves this issue

**Comment by Xurma2** [comment]
Thanks
