### ISSUE TITLE
CRNA branch  - App launch error in expo

### ISSUE THREAD

**Issue by mirzavu** [GeekyAnts/NativeBase-KitchenSink#72]
Tried to run basic app. This is the steps I followed:

1. Cloned CRNA branch
2. npm install
3. react-native link
4. npm start
Saw the splash screen, but could not navigate to anything, no button.

The error from console is:

> Bundling `node_modules/react-native-scripts/build/bin/crna-entry.js`  97.1% (1157/1174), failed.

> error: bundling failed: "Unable to resolve module `react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass` from `/home/hp/projects/NativeBase-KitchenSink/node_modules/react-native-svg/elements/Rect.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."

Tried the steps given in error, but error still persists.

**Comment by kyloe** [comment]
Gettibg exactly the same error here. Seems that there are a number of unresolvable dependency conflicts - many modules require 15.x.x of react where as main package requires 16.0.x - can this be resolved - I'm new to this game.

```
npm WARN react-native-maps@0.15.2 requires a peer of react@>=15.4.0 but none was installed.
npm WARN react-native-branch@2.0.0-beta.3 requires a peer of react@>=15.4.0 but none was installed.
npm WARN lottie-react-native@1.1.1 requires a peer of react@>=15.3.1 but none was installed.
npm WARN @shoutem/animation@0.8.10 requires a peer of react@^15.0.0 but none was installed.
```

If I install 15.4.x then I get complaints about 16.0.x not being available ...

Also - if we ignore the warnings and NPM START - then we get an error indicating that Rect.js is not available - when it does in fact exist int ehnode_module tree at the named location. Have tried following the clear cache instructions  - but makes no difference
```
error: bundling failed: "Unable to resolve module `react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass` from `/home/ian/CloudStation/Projects/NativeBase/NativeBase-KitchenSink/node_modules/react-native-svg/elements/Rect.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache
```

Any pointers much appreciated

**Comment by axcl** [comment]
Same with me 
For links to install the Expo app, please visit https://expo.io.

Logs from serving your app will appear here. Press Ctrl+C at any time to stop.

5:38:29 PM: Bundling `node_modules/react-native-scripts/build/bin/crna-entry.js`  9.1% (348/1154), failed.


5:38:29 PM: error: bundling failed: "Unable to resolve module `react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass` from `/home/trancis15/NativeBase-KitchenSink/node_modules/react-native-svg/elements/Rect.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."

**Comment by kyloe** [comment]
Ok - looks like I have a handle on it.

1. Expo has a fixed dependency of react-native-svg 5.2.0 (node_modules/expo/package.json)
2. This version has outdated path references which are fixed in later versions
3. version 5.4.1 is OK
so 

```
rm - r node_modules
npm install

```
then edit expo/package.json
```
[-] "react-native-svg": "https://github.com/expo/react-native-svg/archive/5.2.0-exp.0.tar.gz"
[+] "react-native-svg": "5.4.1"
``'

then 

```
npm uninstall react-native-svg
npm install
npm start
```
There's probably a more 'correct' way - but this is how I just got there

It still throws a few warnings about deprecated paths - but these are not show stoppers

Have fun.

**Comment by SupriyaKalghatgi** [comment]
yes thats an issue with `react-native-svg`
Not with Expo or NativeBase-KitchenSink

[#401 react-native-svg](https://github.com/react-native-community/react-native-svg/issues/401)

**Comment by SupriyaKalghatgi** [comment]
Fixed with latest [commit](https://github.com/GeekyAnts/NativeBase-KitchenSink/commit/a13b7a078c9507d08317dda5ad25e22cd0cc1777) on branch **CRNA**

Fixed by upgrading expo and react-native versions
