### ISSUE TITLE
Gmail Icon can be seen before opening Bottom Right Fab for the first time

### ISSUE THREAD

**Issue by deadcoder0904** [GeekyAnts/NativeBase-KitchenSink#74]
The bottom fab opening at the top has a little red background showing up of `Gmail` icon
It just gets noticed when opening it for the first time both in `Single FAB` & `Multiple FABs` in the `KitchenSink App`
Not a big issue anywayz 😂 but I thought just might give u a little heads up 😜

**Comment by SupriyaKalghatgi** [comment]
@deadcoder0904 Yes thats known issue for us
Looking into it

**Comment by SupriyaKalghatgi** [comment]
PR for this fix [#1488](https://github.com/GeekyAnts/NativeBase/pull/1448)
