### ISSUE TITLE
Cannot use TouchableHighlight

### ISSUE THREAD

**Issue by mirzavu** [GeekyAnts/NativeBase-KitchenSink#75]
Installed the basic app from CRNA branch.

Tried to import and use TouchableHighlight/TouchableOpacity in js/components/home/index.js. But gives the below error:
![screenshot_2017-09-14-13-04-37-961](https://user-images.githubusercontent.com/4288540/30417470-83f4e0fe-994d-11e7-88b0-14a76e8eb09e.jpeg)

**Comment by SupriyaKalghatgi** [comment]
@mirzavu I tried with `TouchableOpacity` and `TouchableHighlight`
worked fine for me
Please post code snippet for this

**Comment by SupriyaKalghatgi** [comment]
@mirzavu Any updates?
