### ISSUE TITLE
Unable to build on iOS 10/11 on simulator

### ISSUE THREAD

**Issue by gurmukhp** [GeekyAnts/NativeBase-KitchenSink#77]
Unable to build with react-native run-ios

<img src ="https://user-images.githubusercontent.com/899769/30737370-43c36140-9f7e-11e7-8f70-13b530501dae.png"/>

**Comment by SupriyaKalghatgi** [comment]
@gurmukhp Try running it from Xcode

**Comment by GeekRishabh** [comment]
@gurmukhp [see here](https://github.com/react-community/create-react-native-app/issues/418)
