### ISSUE TITLE
Navigator Experimental invalid index -1 replacing route

### ISSUE THREAD

**Issue by basequatro** [GeekyAnts/NativeBase-KitchenSink#8]
When i click two times i've got this error.
Any Idea?

![navexp](https://cloud.githubusercontent.com/assets/2417603/20506321/58ef225e-b03a-11e6-8667-aafc1009c2d1.gif)

**Comment by basequatro** [comment]
the same goes for push...

"should not push route with duplicate key"

**Comment by basequatro** [comment]
Thanks for the feedback NB team

**Comment by krishnalelas** [comment]
Same issue.. @basequatro How you fixed? Can you please share

**Comment by bCliks** [comment]
Same issue.. @basequatro   How you fixed? Can you please share

**Comment by basequatro** [comment]
@bCliks i didn't fixed yet, the problem is with react-native-navigation-redux-helpers lib
you can update to 0.5.0 at least will fix pop, let me know if you have any progress.

**Comment by bCliks** [comment]
Still Struggling. Any help?

**Comment by basequatro** [comment]
@bCliks I suggest you to take a look at ignite, as native base is only layout and don't provide support for unpaid products or this app that\s only a demo. I moved all my applications to ignite as this is a 1 month issue without any answer, i'm also sure that you can't wait this much for a solution that  entitles as missing part of react native, but still missing something.

**Comment by sanketsahusoft** [comment]
@basequatro It's not that we don't provide support for unpaid products. As a part of the Open Source community, we receive a lot of issues and requests. We are a small team and we are trying our level best to catch up with every issue which we can and contribute wherever we can.

I will try to look into it in next couple of days and get back to you. Btw, Ignite is really good. Glad to hear you found a better solution.

One more thing, the intention of this Kitchen Sink app was to demonstrate the use case of NativeBase UI components. Routing was just copied from one of the projects. We don't recommend using this folder structure or pattern in other projects, Ignite solves that problem way better than this KitchenSink app.

With these Open source project, I hope we don't land up in something like [this](https://medium.com/@thejameskyle/dear-javascript-7e14ffcae36c#.sn8vqhoan)
