### ISSUE TITLE
Use of AppNavigator.js in js folder

### ISSUE THREAD

**Issue by pranay414** [GeekyAnts/NativeBase-KitchenSink#82]
I was just looking at the codebase. I don't understand the use of AppNavigator.js in js folder. It's been exported but it is not imported anywhere, isn't it redundant since we again import all the components inside the App.js in js folder.

**Comment by SupriyaKalghatgi** [comment]
@pranay414 Yes, we are aware of it.

Soon we will upgrade NativeBase-KitchenSink, with some structural changes in the repo

**Comment by SupriyaKalghatgi** [comment]
@pranay414 You can check the latest update
