### ISSUE TITLE
Errors in both IOS and Android emulators

### ISSUE THREAD

**Issue by snapnurse-joshuamatthews** [GeekyAnts/NativeBase-KitchenSink#84]
Fresh clone, ran both installation commands, then getting errors on both ios and android emulators. 

On android: 

Unable to load script from  assets 'index.android.bundle'. Make sure your bundle is packages correctly or you're running a packager server

On ios

No bundle URL Present. Make sure you're running a package server or have included a .jsbundle file in your application bundle.

**Comment by SupriyaKalghatgi** [comment]
@snapnurse-joshuamatthews Did you update `package.json` after clone?

**Comment by SupriyaKalghatgi** [comment]
@snapnurse-joshuamatthews Please check with the latest updates
