### ISSUE TITLE
How can I add support for graphs and bar/line charts

### ISSUE THREAD

**Issue by vedbhawsar** [GeekyAnts/NativeBase-KitchenSink#85]

**Comment by SupriyaKalghatgi** [comment]
@vedbhawsar Your requirement is invalid from the purpose of this repo

**Comment by vedbhawsar** [comment]
@SupriyaKalghatgi  I am quite new to the react ecosystem. I need to show line charts in my Android Application. Just wanted to know if **react-native** or **NativeBase** how can we add?

**Comment by SupriyaKalghatgi** [comment]
@vedbhawsar NativeBase does not provide graph features
You can check these packages
https://www.npmjs.com/package/react-native-graphs
https://www.npmjs.com/package/react-native-d3multiline-chart
