### ISSUE TITLE
[exp]Unable to resolve RCTNetworking" 

### ISSUE THREAD

**Issue by vedbhawsar** [GeekyAnts/NativeBase-KitchenSink#86]
When I am building it for production, this error is thrown. I am using instruction from [Here](https://docs.expo.io/versions/latest/guides/building-standalone-apps.html) for building an Expo Standalone App. 

`[exp] Starting build process... 
[exp] Publishing...
[exp] Building iOS bundle
[exp] Building Android bundle
[exp]Unable to resolve RCTNetworking" from ".\\node_modules\\react-native\\Libraries\\Net work\\XMLHttpRequest.js"`

1. `react-native -version`
react-native-cli: 2.0.1
react-native: 0.46.4
2. `node -v`
v9.1.0
3. `npm -v`
5.5.1

This error came when I ran the command `exp build:android`,  while `exp start`  is working good.

**Comment by SupriyaKalghatgi** [comment]
@vedbhawsar Which branch are you referring?
Did you update `package.json`?

**Comment by vedbhawsar** [comment]
@SupriyaKalghatgi  I am using CRNA branch and getting this error when I dispatch the command `exp build:android`.  I didn't update package.json, actually I did, but that run in some dependency issues so I replace the `package.json` and delete `node_module`, and again did a `npm install`.

**Comment by SupriyaKalghatgi** [comment]
@vedbhawsar You can check the latest
