### ISSUE TITLE
How can I use this repo as node dependency in another react-native project?

### ISSUE THREAD

**Issue by anil1712** [GeekyAnts/NativeBase-KitchenSink#87]
Hi,

I need to create multiple react native apps but I want include this "kitchensink" as dependency of another react native project, so that I can add more components (other than nativebase also, like google maps) and will expose the "Map" component from this repo. So it will contain resuable UI components and I can pass the "platform" as props to that components.

Thanks,
Anil

**Comment by SupriyaKalghatgi** [comment]
@anil1712 Did you check SO for this?

**Comment by SupriyaKalghatgi** [comment]
@anil1712 Some [link](https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly) that can help you

**Comment by anil1712** [comment]
@SupriyaKalghatgi actually I am asking to create a local build. 
Let's say I have 3 separate node projects:
1. mobile-ui-components
2. mobile-app1
3. mobile-app2

So I want to import the components from `mobile-ui-components` (which will have all the components) repo for both `mobile-app1` and `mobile-app2`. 

So how to create build for `mobile-ui-components` so that I can use it as npm dependency (locally).

Thanks,
Anil

**Comment by anil1712** [comment]
@SupriyaKalghatgi Can you please suggest me any solution for this.

**Comment by SupriyaKalghatgi** [comment]
@anil1712 https://stackoverflow.com/questions/28728665/how-to-use-private-github-repo-as-npm-dependency
