### ISSUE TITLE
Demo on expo.io not working in latest Expo client

### ISSUE THREAD

**Issue by brownieboy** [GeekyAnts/NativeBase-KitchenSink#89]
I visited URL https://expo.io/@community/nativebase-kitchen-sink with a desktop browser and scanned the QR code with Expo on my iPhone.  The Expo client gives the error :

> This experience uses SDK v13.0.0, but this Expo client requires at least v18.0.0

Expo client is version 2.2.0 running on iOS 10.3.3.

**Comment by SupriyaKalghatgi** [comment]
@brownieboy Delete expo app from your device, install it again and try

**Comment by brownieboy** [comment]
Deleted Expo from my iPhone and then reinstalled from the App Store.  Scanned the QR in again.  I'm getting the same erro as bfore.

**Comment by SupriyaKalghatgi** [comment]
@brownieboy Oops! Thats deprecated
Where did you refer this from?
Check this https://expo.io/@geekyants/nativebasekitchensink

**Comment by brownieboy** [comment]
Okay, the official link works fine, so all good.

I found that other one by going to https://expo.io and searching for "nativebase".  The official link doesn't show up the list of results for some reason!
