### ISSUE TITLE
the mask of android is too smaller in android  6.0

### ISSUE THREAD

**Issue by wuyongyi** [GeekyAnts/NativeBase-KitchenSink#9]
android version: 6.0
screen:1920x1080
problem: when the drawer of kitchensink is open, the dark mask does not cover the other part of the screen(a little small), the ios version is fine.

**Comment by sankhadeeproy007** [comment]
@SupriyaKalghatgi are we using native base drawers here?

**Comment by SupriyaKalghatgi** [comment]
@sankhadeeproy007 Yes

**Comment by SupriyaKalghatgi** [comment]
@wuyongyi Fixed with latest release of NativeBase KitchenSink
