### ISSUE TITLE
can you add a maps template?

### ISSUE THREAD

**Issue by nunziofiore** [GeekyAnts/NativeBase-KitchenSink#90]
I think that your kitchen sink is perfect. Can you add also a map template?
Something link:
- map
- map with a geolocation button
- map with pin clickable and detail view after click.

I think that in this way you have covered all the stuff useful in a kickchen sink.

**Comment by SupriyaKalghatgi** [comment]
@nunziofiore Thank you for your appreciation!
NativeBase KitchenSink is to showcase NativeBase components
So adding maps template is irrelevent
