### ISSUE TITLE
React native version & Expo sdk version incompatible

### ISSUE THREAD

**Issue by uimax** [GeekyAnts/NativeBase-KitchenSink#91]
I want build an Expo "standalone" app to get an IPA/APK for distribution without having to build the native code yourself. But in package NativeBase-KitchenSink v2.4.5 includes: react-native v0.51.0 vs Expo 23

You can refer to the compatible version here: [https://docs.expo.io/versions/latest/sdk/index.html](https://docs.expo.io/versions/latest/sdk/index.html)

**Comment by SupriyaKalghatgi** [comment]
@uimax Can you share the link of `package.json` where you find this mismatch of versions?

**Comment by uimax** [comment]
**@SupriyaKalghatgi** 
This is my `package.json`: https://gyazo.com/727de16ecaf2c81b8a25f490a3ea97fe
I have seen this link [https://docs.expo.io/versions/latest/sdk/index.html#sdk-version](https://docs.expo.io/versions/latest/sdk/index.html#sdk-version) but have not seen **Expo Sdk** support for **React Native** v0.51.0

**Comment by SupriyaKalghatgi** [comment]
@uimax 
> in package NativeBase-KitchenSink v2.4.5 includes: react-native v0.51.0 vs Expo 23
Can you share link for this?

**Comment by uimax** [comment]
https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/package.json

**Comment by SupriyaKalghatgi** [comment]
@uimax The link you shared https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/package.json
This does not include Expo, this is pure RN app
You should go through ReadMe

**Comment by uimax** [comment]
Can you send NativeBase KitchenSink with **React Native** v0.50.0 ? I did not find it in the changelog?
Thanks **@SupriyaKalghatgi** !

**Comment by SupriyaKalghatgi** [comment]
@uimax You can refer releases

**Comment by uimax** [comment]
Ok, @SupriyaKalghatgi ! Thank you so much !
