### ISSUE TITLE
Unable to deploy master branch

### ISSUE THREAD

**Issue by davepile** [GeekyAnts/NativeBase-KitchenSink#96]
I am trying to get this working on Windows 8.1 with Android Emulator. The build seems to succeed  but I get an error on the emaulator "java.util.concurrent.ExecutionException: SyntaxError: Strict mode does not allow function declarations in a lexically nested statement"

This is what I did-
I downloaded the master branch zip file.

I was unable to open this project in the Expo Xde as I got the error message "Error: missing exp.json"

I Installed dependencies once with npm and then after a fresh unpack of the zip file with yarn (after reading some other comments here).

I run npm start

and then run "react-native run-android"  ( I am unable to use "npm run android" as it does not appear in the package.json scripts)

package.json is unmodified from github

**Comment by SupriyaKalghatgi** [comment]
@davepile 
> I downloaded the master branch zip file.
> I was unable to open this project in the Expo Xde as I got the error message "Error: missing exp.json"

You probably missed out going through ReadMe

**Comment by davepile** [comment]
thank you. sorry to waste your time
